# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestCreateuser():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.users = ['test'+str(n) for n in range(100)]
    self.driver.get("http://localhost:3000/article")
    self.driver.set_window_size(1536, 835)
  
  def teardown_method(self, method):
    self.driver.find_element(By.NAME, "user_area").click()
    # self.driver.find_element(By.LINK_TEXT, "Hello*").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    #self.driver.find_element(By.CSS_SELECTOR, ".my-sm-0").click()
    self.driver.quit()
  
  def createuser(self):
    self.driver.find_element(By.CSS_SELECTOR, ".my-2:nth-child(2)").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("test2")
    self.driver.find_element(By.CSS_SELECTOR, ".form-control-plaintext:nth-child(4)").send_keys("test2")
    self.driver.find_element(By.CSS_SELECTOR, ".form-control-plaintext:nth-child(5)").send_keys("test2")
    self.driver.find_element(By.NAME, "password2").send_keys("test2")
    self.driver.find_element(By.NAME, "password2").send_keys(Keys.ENTER)
    #assert self.driver.find_element(By.NAME, "user_area").text == "Hello"

  def test_createuser(self, benchmark):
    benchmark(self.createuser)
  
