# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("http://localhost:3000/article")
    self.driver.find_element(By.ID, "btn").click()
    self.driver.find_element(By.NAME, "search").send_keys("Mario")
    self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.LINK_TEXT, "A Nintendo designer reviews your Super Mario Maker 2 levels").text == "A Nintendo designer reviews your Super Mario Maker 2 levels"
  
